[workspace]

members = [
    "crates/rsonpath",
    "crates/rsonpath-lib"
]

exclude = [
    "crates/rsonpath-benchmarks"
]

[profile.dev]
lto = false

[profile.release]
lto = "thin"
debug = 1

[patch.crates-io]
rsonpath-lib = { path = "./crates/rsonpath-lib" }
