[package]
name = "rsonpath"
version = "0.4.0"
authors = ["Mateusz Gienieczko <mat@gienieczko.com>"]
edition = "2021"
description = "Blazing fast JSONPath CLI application powered by SIMD."
readme = "../../README.md"
license = "MIT"
keywords = ["json", "jsonpath", "query", "simd", "cli"]
categories = [
    "command-line-utilities",
    "text-processing",
    "parser-implementations",
]
repository = "https://github.com/V0ldek/rsonpath"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
clap = { version = "4.1.11", features = ["derive", "wrap_help"] }
color-eyre = { version = "0.6.2", default-features = false }
eyre = "0.6.8"
log = "0.4.18"
rsonpath-lib = { version = "0.4.0", default-features = false }
simple_logger = "4.1.0"

[features]
default = ["simd", "default-optimizations"]
simd = ["rsonpath-lib/simd"]
head-skip = ["rsonpath-lib/head-skip"]
tail-skip = ["rsonpath-lib/tail-skip"]
unique-members = ["tail-skip", "rsonpath-lib/unique-members"]
default-optimizations = ["head-skip", "tail-skip", "unique-members"]
